// Code generated by enum generator; DO NOT EDIT.
package status

import (
	"database/sql/driver"
	"fmt"
)

// JobStatus is the exported type for the enum
type JobStatus struct {
	name  string
	value uint8
}

func (e JobStatus) String() string { return e.name }

// Index returns the underlying integer value
func (e JobStatus) Index() uint8 { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e JobStatus) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *JobStatus) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseJobStatus(string(text))
	return err
}

// Value implements the driver.Valuer interface
func (e JobStatus) Value() (driver.Value, error) {
	return e.name, nil
}

// Scan implements the sql.Scanner interface
func (e *JobStatus) Scan(value interface{}) error {
	if value == nil {
		// try to find zero value
		for _, v := range JobStatusValues {
			if v.Index() == 0 {
				*e = v
				return nil
			}
		}
		// no zero value found, return error
		return fmt.Errorf("cannot scan nil into JobStatus: no zero value defined")
	}

	str, ok := value.(string)
	if !ok {
		if b, ok := value.([]byte); ok {
			str = string(b)
		} else {
			return fmt.Errorf("invalid jobStatus value: %v", value)
		}
	}

	val, err := ParseJobStatus(str)
	if err != nil {
		return err
	}

	*e = val
	return nil
}

// _jobStatusParseMap is used for efficient string to enum conversion
var _jobStatusParseMap = map[string]JobStatus{
	"unknown":  JobStatusUnknown,
	"active":   JobStatusActive,
	"inactive": JobStatusInactive,
	"blocked":  JobStatusBlocked,
}

// ParseJobStatus converts string to jobStatus enum value
func ParseJobStatus(v string) (JobStatus, error) {

	if val, ok := _jobStatusParseMap[v]; ok {
		return val, nil
	}

	return JobStatus{}, fmt.Errorf("invalid jobStatus: %s", v)
}

// MustJobStatus is like ParseJobStatus but panics if string is invalid
func MustJobStatus(v string) JobStatus {
	r, err := ParseJobStatus(v)
	if err != nil {
		panic(err)
	}
	return r
}

// GetJobStatusByID gets the correspondent jobStatus enum value by its ID (raw integer value)
func GetJobStatusByID(v uint8) (JobStatus, error) {
	switch v {
	case 0:
		return JobStatusUnknown, nil
	case 1:
		return JobStatusActive, nil
	case 2:
		return JobStatusInactive, nil
	case 3:
		return JobStatusBlocked, nil
	}
	return JobStatus{}, fmt.Errorf("invalid jobStatus value: %d", v)
}

// Public constants for jobStatus values
var (
	JobStatusUnknown  = JobStatus{name: "unknown", value: 0}
	JobStatusActive   = JobStatus{name: "active", value: 1}
	JobStatusInactive = JobStatus{name: "inactive", value: 2}
	JobStatusBlocked  = JobStatus{name: "blocked", value: 3}
)

// JobStatusValues contains all possible enum values
var JobStatusValues = []JobStatus{
	JobStatusUnknown,
	JobStatusActive,
	JobStatusInactive,
	JobStatusBlocked,
}

// JobStatusNames contains all possible enum names
var JobStatusNames = []string{
	"unknown",
	"active",
	"inactive",
	"blocked",
}

// JobStatusIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all JobStatus values in declaration order. Example:
//
//	for v := range JobStatusIter() {
//	    // use v
//	}
func JobStatusIter() func(yield func(JobStatus) bool) {
	return func(yield func(JobStatus) bool) {
		for _, v := range JobStatusValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ jobStatus = jobStatus(0)
	// This avoids "defined but not used" linter error for jobStatusUnknown
	var _ jobStatus = jobStatusUnknown
	// This avoids "defined but not used" linter error for jobStatusActive
	var _ jobStatus = jobStatusActive
	// This avoids "defined but not used" linter error for jobStatusInactive
	var _ jobStatus = jobStatusInactive
	// This avoids "defined but not used" linter error for jobStatusBlocked
	var _ jobStatus = jobStatusBlocked
	return true
}()
